### ISSUE TITLE
Applescript with emoji icon fail to run

### ISSUE THREAD

**Issue by Pustelto** [raycast/script-commands#55] opened 2020-11-12 04:33 UTC
Hi, 

first of all I want to say that I love what you are doing with Raycast. I'm tweaking it a bit with script and I have bumbed to tricky issue. When I try to run applescript in Raycast to which contains emoji icon it won't run if there is a `tell` block over multiple lines.

I have tried sleep command from this repo and it worked fine. But when I tried to run `toggle-desktop-icons` it failed and nothing happen. I have tried to change mode to `compact` and it write `Operaction couldn't be completed. Exec format error.`. But if I delete `# @raycast.icon` line script works.

macOS version 10.15.7

Tested it with Raycast 1.1.0 and 1.1.1.

**Comment by PitNikola** [comment] 2020-11-15 20:25
Hi @Pustelto. Thanks for reporting. That's indeed a tricky issue. I haven't managed to reproduce this problem locally (macos 10.15.7). Did you see this error when running any other apple scripts with emoji icon?

Also could you try switching mode to `fullOutput` and tell me what do you see there?

**Comment by Pustelto** [comment] 2020-11-16 13:03
Hi, I had this issue on 10.15.x version (not sure about exact version though, and it's still there in macOS 11.0.1). I tested it with my custom apple script to connect to VPN. The issues was the same. Adding `fullOutput` doesn't give much help since there is not error at all (see the attached pic). However if I run the script in Apple's ScriptEditor it works. So problem is probably not with the script itself.

I am running zsh shell v5.8 (x86_64-apple-darwin20.0), if that have any value in this case. Also including screens of my scripts setup.
<img width="728" alt="Snímek obrazovky 2020-11-16 v 14 00 20" src="https://user-images.githubusercontent.com/10606260/99255595-727a3280-2814-11eb-9b4c-3163b56814ff.png">
<img width="725" alt="Snímek obrazovky 2020-11-16 v 14 01 23" src="https://user-images.githubusercontent.com/10606260/99255599-73ab5f80-2814-11eb-83ac-747e07eb5ed7.png">
<img width="758" alt="Snímek obrazovky 2020-11-16 v 13 53 42" src="https://user-images.githubusercontent.com/10606260/99254752-24186400-2813-11eb-8aee-8aee1a7f23b3.png">

**Comment by kastnerorz** [comment] 2020-12-07 12:20
@PitNikola I try to remove `# @racast.icon` but always send me an error :(
Here's my script, may help you to reproduce the issue:

```
#!/usr/bin/osascript
# @raycast.title Open with Chrome
# @raycast.author Siyuan Zhang
# @raycast.authorURL https://github.com/kastnerorz
# @raycast.description Open Current Safari Tab with Chrome
# @raycast.icon 🧭
# @raycast.mode silent
# @raycast.packageName system
# @raycast.schemaVersion 1
tell application "Safari"
	set currentUrl to URL of current tab of front window
end tell
tell application "Google Chrome"
	open location currentUrl
end tell
```

**Comment by thomaspaulmann** [comment] 2020-12-12 11:59
@kastnerorz your script works on my machine. What error do you get when removing the `@raycast.icon` from the script? Also, could you make sure to set the encoding to UTF-8. I attached a screenshot on how to do it in VS Code. We encountered some issues in the [community](http://raycast.com/community) that the encoding was sometimes set to something else for `AppleScript` and it broke the execution.

![CleanShot 2020-12-12 at 11 57 34@2x](https://user-images.githubusercontent.com/12066405/101983199-487c2a80-3c71-11eb-8f42-2ae72b34d38c.png)

**Comment by Pustelto** [comment] 2020-12-12 12:30
@thomaspaulmann I tried to re-save `toggle-desktop-icons.applescript` taken from your repo to UTF-8 (was UTF-16 LE), but after that if I refresh the scripts in raycast settings I don't see the script anymore at all.

**Comment by thomaspaulmann** [comment] 2020-12-12 12:37
That is even weirder. Did you make sure that the script is executable? You can run `chmod +x <path to file>` to make it executable. When you just download the file, the flag is sometimes not set.

**Comment by kastnerorz** [comment] 2020-12-12 17:34
@thomaspaulmann I think it's the encoding issue. I saved it with script editor, after I copy and
re-edit with vim, it works.

**Comment by thomaspaulmann** [comment] 2020-12-12 17:42
Great! I'm gonna close this issue then. Might be worth to add something to the `AppleScript` template or setup.

**Closed by thomaspaulmann** 2020-12-12 17:42 UTC
Labels: bug

**Comment by Pustelto** [comment] 2020-12-14 09:37
@thomaspaulmann I tried to change encoding to UTF-8, but still no success. I still have problems to add icons to some other apple scripts (icon is not displayed). I will try to rewrite non-working apple script from scratch in UTF-8 to double check, but so far this seems like not-working for me. I have checked the permission and I have `execute` permission for all my scripts.

**Comment by santiago-coastpay-com** [comment] 2022-06-27 20:05
In case it is still helpful to anyone:

I just tried creating an applescript script and I got hit with `[Exec format error]` when trying to run it. After reading this thread, removing the default Raycast line `# @raycast.icon 🤖` solved the problem.

**Comment by RobinDaugherty** [comment] 2022-08-17 13:31
This issue is definitely not resolved, it seems to happen with every AppleScript created through Raycast.

Is it possible that when Raycast generates a new AppleScript file, it saves it with the wrong character encoding? At the least, the issue seems to be caused by the Emoji that Raycast is adding to the generated file, and it would be resolved by removing that.

**Comment by mSarheed** [comment] 2023-01-20 11:50
> Also, could you make sure to set the encoding to UTF-8. I attached a screenshot on how to do it in VS Code.
FYI: I was having the same issue. Above suggestion from @thomaspaulmann fixed it. For some reason every time I edit the script in Script Editor it encodes it as UTF-16, and then Raycast won't run the script. Changing the script file to UTF-8 fixes that.

**Comment by thomaspaulmann** [comment] 2023-01-20 14:37
Yeah Script Editor is a bit annoying. I would suggest to edit it in another editor like VS Code.

**Comment by jbueter** [comment] 2023-02-16 10:33
I am not quite sure, whether it is related to this issue, but I have a script that works as expected with Script Editor. As soon as I want to run it with Raycast, the script is not working. I am getting an error that the "tell" command is not found. It is already saved as UTF-8.

**Comment by thomasbaart** [comment] 2023-04-24 12:31
Would be useful to get an error message stating that the file was saved in the wrong encoding. Just spent half an hour troubleshooting due to the Script Editor saving it in UTF16 by default. After setting the encoding to UTF8 it worked again, but the error message I got wasn't helpful:

> Reason: Process tried to run, but failed
> Domain: scripts
> Time: 12:25:51.852
> Underlying: 
> 	Domain: NSPOSIXErrorDomain 8
> 	Reason: Exec format error

I hope by putting this here, people will find the resolution easier. Bonus points if Raycast could hint to the user that the encoding isn't correct.

**Comment by ramnathk** [comment] 2023-10-16 16:34
Adding to the [comment above](https://github.com/raycast/script-commands/issues/55#issuecomment-1520071472) Note that VSCode will give you the encoding in its status bar.

Also @thomasbaart thanks for the Kyria!

**Comment by dudido** [comment] 2024-08-17 20:15
Same issue in 2024. Switching the encoding to UTF-8 in Sublime seems to fix it. Raycast should implement a fix.

**Comment by catAndZ** [comment] 2024-09-24 01:50
> Same issue in 2024. Switching the encoding to UTF-8 in Sublime seems to fix it. Raycast should implement a fix.

here is already a clear solution, and I don’t think it’s too troublesome to implement. As for why the Raycast maintainers haven’t done this, I don’t understand. I support you.

**Comment by 1expel** [comment] 2025-01-17 20:41
Did not try switching the encoding but just deleting the emoji worked for me
