### ISSUE TITLE
Issue parsing specific text combinations from script

### ISSUE THREAD

**Issue by sumpygump** [raycast/script-commands#233] opened 2021-02-17 18:22 UTC
I noticed that when I copy this example code:

```
<?php

sprintf("Hello <fg=yellow>%s</>", "world");
```

And then run the script `create-image-from-code.sh`

It ends up making this as the image:
![image](https://user-images.githubusercontent.com/676007/108248219-2e4f4480-7119-11eb-93d1-7e60788a6cf7.png)

And in this state, the "Download image" doesn't work.

I managed to reduce it to the following code that will produce the issue:

```

<>%s
```

Note that the newline above the line with the `>%s` is required to recreate the error.

I am on MacOS Catalina.

**Comment by sumpygump** [comment] 2021-02-17 18:30
Follow up on this. I ran a test in order to determine whether `base64` was mangling the content before sending it. I added an `echo $CODE` in the script to see what it was producing. I got the string `PD9waHAKCnNwcmludGYoIkhlbGxvIDxmZz15ZWxsb3clcyIsICJ3b3JsZCIpOwo=`

When I run `base64 --decode` on it I get the expected results. So the correct string is being sent up to the server:

```
$ echo PD9waHAKCnNwcmludGYoIkhlbGxvIDxmZz15ZWxsb3clcyIsICJ3b3JsZCIpOwo= | base64 --decode
<?php

sprintf("Hello <fg=yellow%s", "world");
```

**Comment by thomaspaulmann** [comment] 2021-02-17 20:00
Thanks for flagging this. I think the problem is that the `open` command doesn't properly URL encode the query params. Are you on macOS Big Sur?

**Comment by sumpygump** [comment] 2021-02-17 20:25
I am on Catalina. I think you are on to something. I believe it just so happens that the character combination I generate introduces a `+` symbol in the base64 encoded string.

```
https://ray.so/?colors=midnight&background=true&darkMode=true&padding=64&title=Untitled-1&code=PD9waHAKCnNwcmludGYoIkhlbGxvIDxmZz15ZWxsb3c+JXMiLCAid29ybGQiKTsK
```

This will fail (because I think the browser interprets the + symbol as a space.

But when I urlencode the base64 encoded value:

```
https://ray.so/?colors=midnight&background=true&darkMode=true&padding=64&title=Untitled-1&code=PD9waHAKCnNwcmludGYoIkhlbGxvIDxmZz15ZWxsb3c%2BJXMiLCAid29ybGQiKTsK
```

It works!

Based on that it seems the solution is to replace any `+` symbols in the generated CODE query parameter with `%2B`. According to this [doc](https://base64.guru/learn/base64-characters), the only valid output character for a base64 encoded string that would need to be urlencoded is the `+`, so this primitive approach seems adequate.

I can confirm that editing the script to this on lines 36 and 37 solves it (note I just added a bash replace-all syntax to the `$CODE` variable here to replace any `+` with `%2B`).

```
CODE=$(pbpaste | base64)
CODE=${CODE//+/%2B}
```

Let me know if you'd like me to make a pull request for this.

**Comment by thomaspaulmann** [comment] 2021-02-17 21:20
Ah this is brilliant. Please go ahead and submit a PR. Your solutions seems very elegant. Please reference this issue in the PR and then we can close it when it got merged. 

Thanks a lot for digging into it. Super appreciated.

**Comment by thomaspaulmann** [comment] 2021-02-17 22:08
PR merged 👏

**Closed** 2021-02-17 22:08 UTC
