### ISSUE TITLE
Can't type/search in Raycast's on-screen input

### ISSUE THREAD

**Issue by nagyv** [raycast/script-commands#157] opened 2020-12-09 15:42 UTC
## How to reproduce?

1. Hit the Raycast shortcut
2. Type in the input

## Actual behaviour

Input does not work

## Expected behaviour

Input should work

## Context

I've just installed Raycast, and enabled some extensions and added scripts. Typing does not work even after disabling all the extensions.

Raycast did not ask for any permissions.

**Comment by thomaspaulmann** [comment] 2020-12-09 16:07
Thanks for raising this issue. We're currently investigating this bug. Did you set some global hotkeys or aliases in the Shortcuts preferences?

**Comment by nagyv** [comment] 2020-12-09 21:01
First, I've set the recommended Option+Space, then I've set it instead of Spotlight. I've noticed that it does not work at this point.

Resetting to Option+Space did not help.

**Comment by nagyv** [comment] 2020-12-09 21:12
I've uninstalled Raycast, then re-installed, enabled all the extensions and scripts as I wanted, set the shortcut again, and it still works.

I could not reproduce.

If you can reproduce it either, feel free to close the issue.

Thanks for your time!

**Comment by nagyv** [comment] 2020-12-10 22:11
I might have reproduced the issue again.

What I did since yesterday:
- I've read your e-mail about the update
- Installed the update
- Enabled window management
- Set up hotkeys for window management - I've added and removed a hotkey yesterday too, but totally forget out it

**Comment by pacocoursey** [comment] 2020-12-11 00:13
Encountered this just now after enabling Global Hotkeys for Applications. Restarting Raycast worked

**Comment by thomaspaulmann** [comment] 2020-12-11 00:22
Thanks for the reports! We're investigating this nasty bug but seems to be related to hotkeys. Gonna debug harder to figure out what's going on there. Thanks for the hints! I'll keep this issue updated with our findings.

**Comment by hechen** [comment] 2020-12-11 07:58
Today, I encountered this issue either.  Hit global shortcuts to wake Raycast, then typed but nothing showed in the Input field. 

I noticed no cursor was blinking in input bar.

**Comment by hechen** [comment] 2020-12-11 08:13
And I can reproduce this issue by enable the global shortcuts for windows management.

Reproduce Steps:

1.  Enable windows management plugin;
2. Setup the global shortcuts for it;
3. Try these shortcuts for a window;
4. Then Raycast's input field frozen ( bug reproduced).


What I did are shown below when I was trying to reproduce this bug:


## Step 1 
![CleanShot 2020-12-11 at 16 09 46@2x](https://user-images.githubusercontent.com/2241096/101878866-4c557180-3bcb-11eb-831e-9bfc9b4e84fa.png)

## Step 2 
![CleanShot 2020-12-11 at 16 09 09@2x](https://user-images.githubusercontent.com/2241096/101878825-36e04780-3bcb-11eb-94e0-c6f2880c9ac7.png)


## Step 3

Try these shorts, I took the safari for example, move left and right, then center.


## Step 4 
![CleanShot 2020-12-11 at 16 11 11@2x](https://user-images.githubusercontent.com/2241096/101878987-86267800-3bcb-11eb-9f65-558dc9163d69.png)

**Comment by thomaspaulmann** [comment] 2020-12-11 13:37
Oh this is brilliant! Thanks for the exact repo steps. It helps a lot for the investigation. Indeed, we find the root cause and looking into it right now to fix it and hope to ship a hotfix very soon.

**Comment by PitNikola** [comment] 2020-12-11 18:53
We finally found 100% reproducible steps (huge thanks to @tanguyls) and now have a fix for this issue! Will be in the next release. Thanks everyone for reporting and helping with investigation.

**Comment by fe9lix** [comment] 2020-12-14 16:50
Fixed in hotfix release 1.4.1!

**Closed by fe9lix** 2020-12-14 16:50 UTC
Labels: bug
