### ISSUE TITLE
Colored output

### ISSUE THREAD

**Issue by Rukenshia** [raycast/script-commands#22] opened 2020-11-01 09:02 UTC
For scripts that show output, having color codes work would be good:

```sh
echo -e "Hola \033[91mseñor\033[0m"
```

should produce
![image](https://user-images.githubusercontent.com/1899599/97798755-59289200-1c29-11eb-82f5-489461ab689b.png)

but currently results in
![image](https://user-images.githubusercontent.com/1899599/97798760-62196380-1c29-11eb-8796-7a3a8f2d2459.png)

**Comment by thomaspaulmann** [comment] 2020-11-03 22:30
Good one! We'll look into supporting a subset of colors.

**Comment by Fjianchao** [comment] 2020-11-20 09:04
Otherwise, MD output is supported

**Comment by nbstoner** [comment] 2020-11-20 09:05
Otherwise, MD output is supported

**Comment by jkelleyrtp** [comment] 2020-12-07 21:50
> Otherwise, MD output is supported

How does this work?

**Comment by nbstoner** [comment] 2020-12-08 05:36
> > Otherwise, MD output is supported
> 
> How does this work?


It may be out of essence. At present, some scripts command written by myself are expected to have some formats or colors on the output, the links can be opened by clicking, and some generated code fragments can be formatted and so on.  (Well, this paragraph is translated by machine. I hope I can express my thoughts)

**Comment by PitNikola** [comment] 2020-12-08 10:24
Just to clarify: Markdown output is not supported either (and will unlikely to be supported).
Colored output and link parsing is on our list of improvements.

**Comment by PitNikola** [comment] 2021-02-18 16:21
Support for colored output has been finally added in 1.8.0. Closing the issue.

**Closed by PitNikola** 2021-02-18 16:21 UTC
Labels: enhancement

**Comment by BoyangMichael** [comment] 2021-02-19 10:42
Nice to have the colored output feature! However, there's still some issues that it does not distinguish between normal and dim. And the escape sequence generated by `tput sgr0` does not seems to be interpreted correctly.

`
echo "Hello!"; 
echo "$(tput setaf 8)Hello!$(tput sgr0)"; 
echo "$(tput setaf 1)Hello!$(tput sgr0)";
`

![Screen Shot 2021-02-19 at 11 35 58 AM](https://user-images.githubusercontent.com/42609034/108494116-74d2a980-72a7-11eb-90bc-e04e08f9ad64.png)

**Comment by PitNikola** [comment] 2021-02-19 11:21
Thanks for reporting @BoyangMichael, we'll take a look into it

**Comment by grzegorzkrukowski** [comment] 2021-03-03 18:46
@BoyangMichael we currently support only limited subset of terminal codes. For now those are only 8-bit foreground and background colours in linux format. We will extend supported range of terminal codes in future.

It seems you are using`xterm` style - you can switch to linux format adding `export TERM=linux` on top of your script.
That will allow you to play around with foreground, background colours and fix the problem with reset `[0m` escape code.

**Comment by BoyangMichael** [comment] 2021-03-03 19:16
> @BoyangMichael we currently support only limited subset of terminal codes. For now those are only 8-bit foreground and background colours in linux format. We will extend supported range of terminal codes in future.
> 
> It seems you are using`xterm` style - you can switch to linux format adding `export TERM=linux` on top of your script.
> That will allow you to play around with foreground, background colours and fix the problem with reset `[0m` escape code.

@grzegorzkrukowski Thanks a lot for the answer! It is very helpful! The problem is solved after switching from `xterm` to `linux`.

**Comment by grzegorzkrukowski** [comment] 2021-03-09 02:11
Updated Readme should now clarify the limitations of current implementation:
https://github.com/raycast/script-commands/blob/master/README.md#ansi-escape-codes---coloured-output
