### ISSUE TITLE
Raycast is preventing Mac sleeping

### ISSUE THREAD

**Issue by elonj** [raycast/script-commands#97] opened 2020-11-21 17:33 UTC
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/56976129/99883466-863ee380-2bdc-11eb-91f7-323268a597bd.png">
Raycast is preventing Mac sleeping

**Comment by thomaspaulmann** [comment] 2020-11-22 23:39
Did you run a specific command? Which version do you use? We don't set anything specific and it doesn't show up as "preventing sleep" for me.

**Comment by elonj** [comment] 2020-11-23 07:31
I just installed the Raycast and I did not run any command. I installed the version 1.0, then I updated it to v1.2.0. They are both preventing sleep. I am running Big Sur 11.0.1. I don't know what to show because I don't see any reason preventing sleep either. Thanks though.

**Comment by joe-zhang3** [comment] 2020-11-24 02:22
@elonj Can you try to uninstall Raycast and see what happens? I am using Raycast on both my MBP and a hackintosh with macOS Big Sur, no sleep problems that I am aware of.

**Comment by elonj** [comment] 2020-11-24 16:47
> @elonj Can you try to uninstall Raycast and see what happens? I am using Raycast on both my MBP and a hackintosh with macOS Big Sur, no sleep problems that I am aware of.

I did try uninstall and install. It turned out to be the same result. No clue at all.

**Comment by PitNikola** [comment] 2020-12-03 17:01
Hi @elonj, does it still happen? None of our team members managed to reproduce it and it's the first report of this kind. Not sure what could possible cause it...

**Comment by elonj** [comment] 2020-12-04 15:52
> Hi @elonj, does it still happen? None of our team members managed to reproduce it and it's the first report of this kind. Not sure what could possible cause it...

Yes, it still happens even though I updated it to v1.3.0. And I don't think I made special settings in Raycast.
![Xnip2020-12-04_07-46-27](https://user-images.githubusercontent.com/56976129/101184462-99eb4080-3605-11eb-8f5f-bd5dfdd375f9.jpg)
![Xnip2020-12-04_07-46-40](https://user-images.githubusercontent.com/56976129/101184465-9a83d700-3605-11eb-832a-933e78781a3c.jpg)
![Xnip2020-12-04_07-49-00](https://user-images.githubusercontent.com/56976129/101184466-9a83d700-3605-11eb-83c1-c7e824da02c7.jpg)
![Xnip2020-12-04_07-49-08](https://user-images.githubusercontent.com/56976129/101184467-9b1c6d80-3605-11eb-9853-fa0543e6db57.jpg)
![Xnip2020-12-04_07-49-15](https://user-images.githubusercontent.com/56976129/101184468-9b1c6d80-3605-11eb-8582-8c1da598b8e8.jpg)

**Comment by fe9lix** [comment] 2020-12-14 16:50
Closing for now since we seem unable to reproduce it with different machines and macOS versions.

**Closed by fe9lix** 2020-12-14 16:50 UTC
Labels: bug
