### ISSUE TITLE
My script commands is occasionally missing

### ISSUE THREAD

**Issue by JasonBoy** [raycast/script-commands#858] opened 2023-07-17 03:37 UTC
My script commands sometimes gone, I need to remove the dir(the dir is a from inside a  Dropbox dir) and add it again, nor sure if it's related to Cloud Sync, I have two macs using the app

<img width="996" alt="image" src="https://github.com/raycast/script-commands/assets/2911620/bf0090bc-aee2-4249-8f45-fefc656eccc7">

**Comment by dehesa** [comment] 2023-07-17 11:23
Hi @JasonBoy, thank you for the report. This is interesting and probably @nhojb would like to know more about it.

Just to be sure, you do have the Pro subscription and Cloud Sync enabled, right?

**Comment by JasonBoy** [comment] 2023-07-17 14:30
@dehesa Yes, I have the Pro subscription and Cloud Sync enabled

**Comment by dehesa** [comment] 2023-07-18 06:05
Ok, we will look into it, but it might take a while to report back (half of the team is on holidays).

**Comment by dehesa** [comment] 2023-07-25 08:45
Hi @JasonBoy,

We have been looking into this issue and we believe we know the problem. We are working on a fix and we will probably release something soon.

Thank you for reporting.

**Comment by JasonBoy** [comment] 2023-08-01 00:13
thanks, one more thing I found is that sometime later, the `Cloud Sync` is turned off after putting the mac back from sleeping

**Comment by nhojb** [comment] 2023-08-02 09:13
Thanks for the bug report - we've had a few users report the same thing. We're going to release an update today which should improve initialization of Cloud Sync. We've also added additional logging to help diagnose the problem if it occurs again.

Regarding the script commands issue we're still investigating this.

**Comment by nhojb** [comment] 2023-08-03 11:44
@JasonBoy the only way I've managed to reproduce this is as follows:

1. Mac A: Adds a Script Commands directory which does not exist on Mac B
2. Mac B: The Script Commands directories setting is synced. But because the directory added in step 1 does not exist Raycast cannot monitor the directory for changes.
3. Mac B: The directory is created (either by the user, or synced by the cloud storage service). However the scripts are not detected by Raycast because it is not monitoring the directory from step 2.
4. The only way to reload the scripts is to a) restart Raycast or b) remove and re-add the directory on Mac B

Do you think this might explain the missing scripts in your case? We should be able to fix this by monitoring a parent directory at step 2. Currently if a Script Commands directory does not exist it just gets ignored as described.

If instead I add a Script Commands directory which exists on both Macs, then the scripts are always detected as expected. Even if they need to be downloaded from cloud storage.

<img width="1112" alt="Screenshot 2023-08-03 at 10 47 44" src="https://github.com/raycast/script-commands/assets/312540/eb2277ec-8bc1-4440-8b97-ee0b982f2a02">

**Comment by JasonBoy** [comment] 2023-08-04 00:50
@nhojb yes thanks, that might explain the case, 
regarding the solution in step 4 a), Raycast may already restarted several times because of the updates, in which case the "missing scripts" case still occurs

**Comment by nhojb** [comment] 2023-08-04 09:21
If the issue does occur again then could you grab some logs.

1. Run this command in the Terminal: `log stream --predicate "subsystem == 'com.raycast.macos'" --level debug --style compact >> ~/Desktop/ray.$(date +%Y%m%d_%H%M%S).log`
2. Run the `Reload Script Directories` command
3. Send the log to john at raycast.com

**Comment by dehesa** [comment] 2023-08-16 14:11
I will be closing this for now, but please feel free to open it if there are new information.

**Closed by dehesa** 2023-08-16 14:11 UTC
Labels: bug

**Comment by simonkotwicz** [comment] 2023-08-17 18:44
Whenever I restart my laptop my script commands are also missing. I need to remove the directory and re-add it for the script commands to appear again. I don't have the Pro subscription.

**Comment by nhojb** [comment] 2023-08-18 08:06
@simonkotwicz what is the path to the directory you are using for script commands? Is it a cloud storage location (iCloud Drive, Dropbox etc)?

**Comment by simonkotwicz** [comment] 2023-08-18 08:12
@nhojb yes it is, I was actually going to mention that.

**Comment by nhojb** [comment] 2023-08-18 08:29
Which service are you using? I'm guessing the path is either `~/Documents/...` (for iCloud Drive) or `~/Library/CloudStorage/...` for Dropbox, OneDrive etc?

**Comment by simonkotwicz** [comment] 2023-08-18 17:04
@nhojb yes `~/Library/CloudStorage/...` for Dropbox

**Comment by simonkotwicz** [comment] 2024-05-08 16:14
@nhojb was this never fixed?
