### ISSUE TITLE
Configure Bitwarden CLI path

### ISSUE THREAD

**Issue by AllenWrenches** [raycast/script-commands#614] opened 2021-11-01 20:06 UTC
I'm trying to use the Bitwarden commands. I didn't have bitwarden-cli installed properly at first, but now I have bitwarden-cli working properly in the terminal (I'm able to run commands such as `bw login` and `bw unlock`) But in Raycast when I try to use Bitwarden script commands I'm getting an error message that says:

**The Bitwarden CLI was not found
Please check that:**

1. The Bitwarden CLI is correctly installed
2. The path of the installation matches the Bitwarden CLI Installation Path extension setting

Currently set to:  undefined

Running `which bw` returns:
/opt/homebrew/bin/bw

How do I add this information to the Raycast path so that it can find the Bitwarden CLI?

**Comment by dehesa** [comment] 2021-11-08 09:25
Hey @AllenWrenches,

Sorry it took so long to answer you. I am sadly not very familiar with Bitwarden. Maybe @PSalant726, @MarcelBochtler, or @jaklan can provide some of their wisdom. In any case, it is best to ask these type of questions in the [Slack Community](https://www.raycast.com/community) when possible.

**Comment by MarcelBochtler** [comment] 2021-11-08 09:36
Hi @AllenWrenches,
unfortunately Raycast has issues with handling custom `PATH`s. See: https://github.com/raycast/script-commands/issues/77
As far as I know `/opt/homebrew/bin` is not available in `PATH` by default.

You can fix this by replacing the `bw` calls with the absolute directory `/opt/homebrew/bin/bw`.

I did it like this in the `search-vault-items.sh` script:
```sh
BW="/opt/local/bin/bw"
JQ="/opt/local/bin/jq"

if ! command -v $BW &> /dev/null; then
  echo "The Bitwarden CLI is not installed (https://bitwarden.com/help/article/cli/)."
  echo "Install via Homebrew with 'brew install bitwarden-cli'"
  exit 1
elif ! command -v $JQ &> /dev/null; then
  echo "The jq utility is not installed (https://stedolan.github.io/jq/)."
  echo "Install via Homebrew with 'brew install jq'"
  exit 1
fi
...
$BW unlock --check $session_args > /dev/null 2>&1
...
output_format="{ name, username: .login.username, $password uris: [.login.uris[]?.uri], lastUpdated: .revisionDate, notes $fields }"
$BW list items $session_args --search "$1" | $JQ --color-output "map($output_format)"
```

**Comment by MarcelBochtler** [comment] 2021-11-08 09:43
Alternatively you can use the new [bitwarden extension](https://github.com/raycast/extensions).
This asks explicitly for the `bw` executable path.

**Comment by svzi** [comment] 2021-11-30 13:46
@MarcelBochtler I'm experiencing the same issues like @AllenWrenches , except that I had installed the Bitwarden CLI via NPM. I would like to use the new bitwarden extension, but for whatever reason I need to have a `client_id` and `client_secret` in order to login. But I'm not using the official Bitwarden, but the open source version Vaultwarden (see https://github.com/dani-garcia/vaultwarden). 

Sadly there is no `client_id` or `client_secret` in my account listed. I've configured the bitwarden cli to work like a charm without, so why I need this here? Why can't I just login via email and password instead?

**Comment by MarcelBochtler** [comment] 2021-11-30 13:54
> I'm experiencing the same issues like @AllenWrenches , except that I had installed the Bitwarden CLI via NPM.

The scripts mentioned in this issue should work with Vaultwarden, if you add the workarounds I mentioned earlier: https://github.com/raycast/script-commands/issues/614#issuecomment-962971172.

I'm not the author of the bitwarden extension, but I guess that it won't work with Vaultwarden as of now.

**Comment by MarcelBochtler** [comment] 2021-11-30 15:00
@thomaspaulmann can this issue be closed as this issue is caused by https://github.com/raycast/script-commands/issues/77?

**Comment by PSalant726** [comment] 2021-11-30 15:09
@svzi 

> for whatever reason I need to have a `client_id` and `client_secret` in order to login

This is now the recommended installation pattern when using the Bitwarden CLI via programmatic means. The changes have been thoroughly documented through issues and PRs related to this extension.

> But I'm not using the official Bitwarden, but the open source version Vaultwarden (see https://github.com/dani-garcia/vaultwarden). 

1. This extension makes no support guarantees for Vaultwarden. It is purely a Bitwarden (official CLI builds) extension.
1. Bitwarden is itself open source

> Why can't I just login via email and password instead?

There is a "legacy" _Log In_ command that authenticates using your email, master password, and [optionally] an MFA code.

**Comment by PSalant726** [comment] 2021-11-30 15:52
> How can I use it with the extension?

You cannot. It's a script command available in this repository. Please review the documentation.

**Comment by svzi** [comment] 2021-11-30 16:00
> You cannot. It's a script command available in this repository. Please review the documentation.

The scripts are working with the aforementioned modification by @MarcelBochtler . I just hoped that I could use the "new" extension as well.

> Bitwarden is itself open source

That's true for sure. But you can't selfhost it without the need to pay for a license, if you need more than one account (as I do). That's probably one of the reasons why Vaultwarden is more loved by the community as the official Bitwarden server implementation (12k stars compared with 8k stars). 

But anyway, thanks for your support @PSalant726 ! 🎉

**Comment by PSalant726** [comment] 2021-11-30 16:05
> without the need to pay for a license

I prefer to support the continued development of great products, when I can find them. I recommend you do the same.

**Comment by svzi** [comment] 2021-11-30 16:17
Thanks for the advice, but believe it or not I have been paying for good open source software voluntarily for years. 

What I don't like, however, is being forced to pay to use certain features (at least not for so called "open source software"). If I host the software myself, there is no further ongoing cost to the company as a result. However, if I use the vendor's infrastructure, then it is only fair that I pay for the provision.

But I honestly don't know what this discussion is about. It is a bit offtopic right now.

**Comment by PSalant726** [comment] 2021-11-30 16:34
> If I host the software myself, there is no further ongoing cost to the company as a result.

Continued development and maintenance is an ongoing cost.

> But I honestly don't know what this discussion is about. It is a bit offtopic right now.

Admittedly this went off topic, but my larger annoyances are:
- You left [a comment](https://github.com/raycast/script-commands/issues/614#issuecomment-982651099) describing an inability to use the _extension_, while this repository only maintains the package of _script commands_.
- The solution to your problem was well understood, documented, and implemented before you even left your comment. It was described in the two comments left immediately prior to yours.
- You are advocating for pivots to a freely available superset of paid Bitwarden features that don't necessarily adhere to the same security audit guarantees, and reduces revenue to the organization that maintains the foundational features required for your recommended alternative to exist.

**Comment by svzi** [comment] 2021-11-30 16:57
> Continued development and maintenance is an ongoing cost.

If you need that to be covered, then oss might not be the perfect fit for it. And for sure nobody is forcing an open source developer to do endless development and maintaining. I know that almost everyone is expecting it for sure, and even most people take it for granted, but it's not. The beauty of open source is that everyone should be able to contribute to the product. If one person doesn't have the time, energy or need to continue to do it, then someone else can step up.

> You left a comment describing an inability to use the extension, while this repository only maintains the package of script commands.

Yeah shame on me. That is inexcusable. Btw did you notice that I only responded to @MarcelBochtler regarding his hint about the extension? Anyway, if that's something that makes you annoyed, then I'm really sorry. 🙏 

> The solution to your problem was well understood, documented, and implemented before you even left your comment. It was described in the two comments left immediately prior to yours.

I'm really sorry that I felt like it was okay saying "hey, the thread starter is not the only one experiencing it". For me as a developer myself it's always interesting to see how many people have a specific issue. When one person tells me that something isn't working as expected, that could be fine in some cases. But when I noticed that more than one person is affected, it could be worth thinking about another solution besides waiting for issue #77 to be resolved. But that is just my thinking.

And a workaround was already provided as you mentioned.

> You are advocating for pivots to a freely available superset of paid Bitwarden features that don't necessarily adhere to the same security audit guarantees, and reduces revenue to the organization that maintains the foundational features required for your recommended alternative to exist.

Maybe you should take some deep breath and don't took everything personal. Also you may avoid shooting the messenger. I don't develop Vaultwarden. I don't advocate people to use it instead of Bitwarden. I just explained my point of view. Sorry that it differs from your. I also explained parts of my philosophy why I dislike the need to pay for certain features of an open source product. 

You don't need to share my thoughts, but I really hope they won't annoy you. Life is too short to get annoyed by this. 🤞 
 Live and let live. ☮️

**Comment by svzi** [comment] 2021-12-06 15:12
@thomaspaulmann I've already cloned the scripts and made the necessary modifications. So everything is up and running.

Additionally I've cloned the extensions repo and played around with the extension. It wouldn't be hard to make the necessary modifications for Vaultwarden (just add the legacy login method). But I doubt it would be a good choice to add a login method, that isn't recommended for the official Bitwarden server, as @PSalant726 already pointed out correctly. So I decided against doing it.

I will wait for the Vaultwarden team to add the API key support as well or just go with the scripts. Thanks for your feedback!

**Closed** 2021-12-31 11:21 UTC
